### ISSUE TITLE
Definir Engine a ser utilizada

### ISSUE THREAD

**Issue by thiagoiferreira** [2018-2-Desenho/CabecaVoleiJoelhoPe#15]
Ao analisar as possíveis engines, considerar a facilidade de implementação do jogo que foi idealizado.
IE, ver se a engine possui funções de física imbutidas.

**Comment by thiagoiferreira** [comment]
Algumas opções de Engine para Java disponíveis:
LibGDX - https://libgdx.badlogicgames.com
LWJGL - https://www.lwjgl.org/
JMonkeyEngine - http://jmonkeyengine.org/

**Comment by lukassxp** [comment]
Ficou decidido pelo grupo utilizar apenas as bibliotecas Graphics 2D e Geom que vem junto a instalação do JDK 8, tendo em vista após alguns estudos sobre a complexidade julgamos que os recursos que tais bibliotecas disponibilizam ao menos por hora parecem suficientes para o desenvolvimento do jogo. No momento considero essa issue como concluída, caso ao longo do desenvolvimento o grupo entenda que é melhor reavaliar a decisão a issue deve ser reaberta e as devidas justificativas devem ser dadas através dos comentários.
