### ISSUE TITLE
Documentar sobre as tecnologias a serem utilizadas

### ISSUE THREAD

**Issue by thiagoiferreira** [2018-2-Desenho/CabecaVoleiJoelhoPe#16]
- [ ] Java
- [ ] Engine

**Comment by lukassxp** [comment]
A questão da engine foi discutida na issue #15 e a versão do JDK utilizada será a 8, não vejo necessidade de documentar sobre essas tecnologias visto que as mesmas já possuem documentação oficial bem grande e completa, além do que as escolhas já foram devidamente justificadas em #15 e no plano de [GCS](https://github.com/2018-2-Desenho/CabecaVoleiJoelhoPe/wiki/Plano-de-Gest%C3%A3o-Configura%C3%A7%C3%A3o-de-Software) . Gostaria do posicionamento do grupo, para decidirmos se a issue deve ser fechada.

**Comment by LucasLermen** [comment]
> A questão da engine foi discutida na issue #15 e a versão do JDK utilizada será a 8, não vejo necessidade de documentar sobre essas tecnologias visto que as mesmas já possuem documentação oficial bem grande e completa, além do que as escolhas já foram devidamente justificadas em #15 e no plano de [GCS](https://github.com/2018-2-Desenho/CabecaVoleiJoelhoPe/wiki/Plano-de-Gest%C3%A3o-Configura%C3%A7%C3%A3o-de-Software) . Gostaria do posicionamento do grupo, para decidirmos se a issue deve ser fechada.

Concordo
