### ISSUE TITLE
Configurar ambiente

### ISSUE THREAD

**Issue by GuiMarques98** [2018-2-Desenho/CabecaVoleiJoelhoPe#19]
- [x] Configurar CodeClimate
 - [x] Configurar o Travis CI

**Comment by lukassxp** [comment]
A principio a configuração foi concluída no repositório, e as respectivas instruções de configuração local de ambiente foram passadas aos membros do grupo. Foi redigido também um Plano de Gerencia e Configuração de Software conforme solicitado na issue #4 que apresenta detalhes justificativa da escolha das ferramentas. Por hora considero a configuração concluída, caso haja necessidade do uso de novas ferramentas ou correção nas configurações a issue deve ser reaberta.
