### ISSUE TITLE
TS05 - Criar classe Game

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#32]
Eu, como desenvolvedor, desejo criar a classe Game.

**Tasks**:
- [ ] Utilizar a estrutura do Main Loop

**Comment by lukassxp** [comment]
Foi criada a classe Game, no entanto o grupo em conjunto optou por não utilizar mais a estrutura do MainLoop levando em consideração o deadline do trabalho estar próxima e termos enfrentado problemas de integração das classes feitas previamente pelo grupo. No lugar do MainLoop entrou uma estrutura chamada GameManager que foi escolhida pois o membro @lukassxp já havia usado uma estrutura semelhante em testes que vinha fazendo ao longo do semestre, o que tornou a implantação dessa estrutura mais comoda ao grupo do que viria a ser a utilização do MainLoop. 
Como a resolução parcial dessa Issue demandou muito mais tempo e esforço que o esperado sugiro que ela seja fechada nesse momento e as tarefas restantes sejam divididas em novas Issues para que possamos repartir o trabalho entre o grupo a fim de conseguir entregar o projeto a tempo.
