### ISSUE TITLE
Fazer as estimativas/planos relacionados ao projeto

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#4]
- [x] Plano de Riscos - @LucasSiqz  e @LucasLermen 
- [x] Plano de Prazos - @gabrielademoraes  e @EduardoBrasil 
- [x] Plano de Custos - @thiagoiferreira  e @Poulvilho 
- [x] Plano de Gestão e Configuração de Software - @lukassxp @GuiMarques98 @LucasPenido

**Comment by lukassxp** [comment]
Plano de GCS finalizado, aguardando revisão.

**Comment by LucasLermen** [comment]
> Plano de GCS finalizado, aguardando revisão.

Plano de GCS revisado @gabrielademoraes @LucasLermen
